export const locations = [
  { name: 'Pune', slug: 'pune' },
  { name: 'Pimpri-Chinchwad', slug: 'pimpri-chinchwad' },
  { name: 'Wakad', slug: 'wakad' },
  { name: 'Thergaon', slug: 'thergaon' },
  { name: 'Akurdi', slug: 'akurdi' },
  { name: 'Baner', slug: 'baner' },
  { name: 'Chinchwadgaon', slug: 'chinchwadgaon' },
  { name: 'Ravet', slug: 'ravet' },
  { name: 'Balewadi', slug: 'balewadi' },
  { name: 'Marunji', slug: 'marunji' },
  { name: 'Aundh', slug: 'aundh' },
  { name: 'Sangvi', slug: 'sangvi' },
  { name: 'Kothrud', slug: 'kothrud' },
  { name: 'Warje', slug: 'warje' },
  { name: 'Katraj', slug: 'katraj' },
  { name: 'Narhe', slug: 'narhe' },
  { name: 'Ambegaon', slug: 'ambegaon' },
  { name: 'Swargate', slug: 'swargate' },
  { name: 'Hadapsar', slug: 'hadapsar' },
  { name: 'Mundhwa', slug: 'mundhwa' },
  { name: 'Kharadi', slug: 'kharadi' },
  { name: 'Viman Nagar', slug: 'viman-nagar' },
  { name: 'Lohegaon', slug: 'lohegaon' },
  { name: 'Kalyani Nagar', slug: 'kalyani-nagar' },
  { name: 'Yerawada', slug: 'yerawada' },
  { name: 'Vishrantwadi', slug: 'vishrantwadi' },
  { name: 'Bhosari', slug: 'bhosari' },
  { name: 'Moshi', slug: 'moshi' },
  { name: 'Chikali', slug: 'chikali' },
  { name: 'Nigadi', slug: 'nigadi' },
  { name: 'Hinjewadi', slug: 'hinjewadi' },
  { name: 'Bavdhan', slug: 'bavdhan' },
  { name: 'Chakan', slug: 'chakan' },
  { name: 'Keshav Nagar', slug: 'keshav-nagar' },
  { name: 'Madunge', slug: 'madunge' },
];

export const searchTerms = [
  'RO Service near me',
  'RO Repair near me',
  'RO repair services near me',
  'Industrial RO service near me',
  'Water purifier service near me',
  'RO water purifier service near me',
  'RO installation near me',
  'RO AMC Service near me',
  'Best RO service near me',
  'Kent RO Service near me',
  'RO shop near me',
  'RO Purifier near me',
  'RO Repairing Shop near me',
  'RO Water Purifier Repair Shop near me',
  'RO Filter Change near me',
  'RO Service Center near me',
  'Water Purifier Installation near me',
  'Aquaguard RO Service near me',
];
